name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your branch is 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (force add vite)
        run: |
          npm install
          npm install vite @vitejs/plugin-react --save-dev

      - name: Build project
        run: npx vite build   # 👈 use npx instead of npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
